import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "node",
    include: ["src/**/*.test.ts"],
    coverage: {
      provider: "v8",
      include: [
        "src/core/di/ServiceContainer.ts",
        "src/core/services/extension/BlockRegistry.ts",
        "src/core/services/extension/GeneratorRegistry.ts",
        "src/core/services/extension/CategoryRegistry.ts",
        "src/core/services/extension/ComponentRegistry.ts",
        "src/core/services/extension/ValidationRegistry.ts",
        "src/core/services/extension/LibraryRegistry.ts",
        "src/core/services/extension/ExampleRegistry.ts",
        "src/core/services/extension/AssetRegistry.ts",
        "src/core/services/extension/CommandRegistry.ts",
        "src/core/services/extension/EventBus.ts",
        "src/core/services/extension/ExtensionContext.ts",
        "src/core/services/extension/ExtensionLoader.ts",
        "src/core/services/extension/ExtensionManager.ts",
        "src/core/services/logging/LoggerService.ts",
        "src/core/services/settings/SettingsManager.ts",
        "src/core/services/theme/ThemeService.ts",
        "src/core/services/i18n/LanguageManager.ts",
        "src/core/services/notification/NotificationService.ts",
        "src/core/services/dialog/DialogService.ts",
        "src/core/services/error/ErrorHandler.ts",
        "src/core/services/hardware/connections/USBConnection.ts",
        "src/core/services/hardware/connections/SerialConnection.ts",
        "src/core/services/hardware/connections/BluetoothConnection.ts",
        "src/core/services/hardware/connections/WiFiConnection.ts",
        "src/core/services/hardware/HardwareManager.ts",
        "src/core/services/port/PortManager.ts",
        "src/core/services/device/DeviceManager.ts",
        "src/core/services/compatibility/CompatibilityService.ts",
        "src/core/services/hardware/HardwareEvents.ts",
        // Phase 9A - Upload Framework
        "src/core/services/upload/UploadEngineRegistry.ts",
        "src/core/services/upload/UploadManager.ts",
        "src/core/services/upload/UploadEvents.ts",
        // Phase 9B - AVR Upload Engine
        "src/core/services/upload/avr/AvrUploadEngine.ts",
        "src/core/services/upload/avr/AvrBoardProfile.ts",
        "src/core/services/upload/avr/Stk500V1Protocol.ts",
        "src/core/services/upload/avr/Stk500V2Protocol.ts",
        // Phase 9C - Toolchain & Backend Abstraction
        "src/core/services/upload/UploaderBackendRegistry.ts",
        "src/core/services/upload/ToolchainManager.ts",
        "src/core/services/upload/backends/AvrdudeBackend.ts",
        "src/core/services/upload/backends/MockBackend.ts",
        // Phase 10 - ESP32 Upload Engine
        "src/core/services/upload/esp32/Esp32UploadEngine.ts",
        "src/core/services/upload/esp32/EsptoolProtocol.ts",
        "src/core/services/upload/esp32/EspResetStrategy.ts",
        "src/core/services/upload/esp32/EspBootMode.ts",
        "src/core/services/upload/backends/EsptoolBackend.ts",
        // Phase 11 - Build System
        "src/core/services/build/BuildEngineRegistry.ts",
        "src/core/services/build/BuildManager.ts",
        "src/core/services/build/BuildCache.ts",
        "src/core/services/build/MockBuildEngine.ts",
      ],
      exclude: [
        "src/**/*.test.ts",
        "src/**/*.d.ts",
        "src/core/types/**",
      ],
      thresholds: {
        "src/core/di/ServiceContainer.ts": { statements: 95, branches: 90, functions: 100, lines: 95 },
        "src/core/services/extension/BlockRegistry.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "src/core/services/extension/GeneratorRegistry.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "src/core/services/extension/CategoryRegistry.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "src/core/services/extension/ComponentRegistry.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "src/core/services/extension/LibraryRegistry.ts": { statements: 100, branches: 85, functions: 100, lines: 100 },
        "src/core/services/extension/ExampleRegistry.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "src/core/services/extension/AssetRegistry.ts": { statements: 80, branches: 50, functions: 100, lines: 80 },
        "src/core/services/extension/EventBus.ts": { statements: 95, branches: 90, functions: 100, lines: 95 },
        "src/core/services/extension/ExtensionContext.ts": { statements: 45, branches: 0, functions: 59, lines: 45 },
        "src/core/services/extension/ExtensionLoader.ts": { statements: 70, branches: 35, functions: 50, lines: 75 },
        "src/core/services/extension/ExtensionManager.ts": { statements: 60, branches: 50, functions: 75, lines: 60 },
        "src/core/services/extension/ValidationRegistry.ts": { statements: 35, branches: 15, functions: 65, lines: 35 },
        "src/core/services/logging/LoggerService.ts": { statements: 95, branches: 65, functions: 95, lines: 95 },
        "src/core/services/settings/SettingsManager.ts": { statements: 90, branches: 75, functions: 80, lines: 90 },
        "src/core/services/theme/ThemeService.ts": { statements: 85, branches: 50, functions: 85, lines: 85 },
        "src/core/services/i18n/LanguageManager.ts": { statements: 85, branches: 65, functions: 85, lines: 85 },
        "src/core/services/notification/NotificationService.ts": { statements: 90, branches: 80, functions: 90, lines: 90 },
        "src/core/services/dialog/DialogService.ts": { statements: 90, branches: 70, functions: 90, lines: 90 },
        "src/core/services/error/ErrorHandler.ts": { statements: 80, branches: 65, functions: 80, lines: 85 },
        "src/core/services/hardware/connections/USBConnection.ts": { statements: 85, branches: 70, functions: 95, lines: 95 },
        "src/core/services/hardware/connections/SerialConnection.ts": { statements: 60, branches: 50, functions: 40, lines: 60 },
        "src/core/services/hardware/connections/BluetoothConnection.ts": { statements: 50, branches: 50, functions: 30, lines: 50 },
        "src/core/services/hardware/connections/WiFiConnection.ts": { statements: 50, branches: 50, functions: 30, lines: 50 },
        "src/core/services/hardware/HardwareManager.ts": { statements: 90, branches: 75, functions: 90, lines: 90 },
        "src/core/services/port/PortManager.ts": { statements: 90, branches: 75, functions: 90, lines: 90 },
        "src/core/services/device/DeviceManager.ts": { statements: 90, branches: 65, functions: 90, lines: 90 },
        "src/core/services/compatibility/CompatibilityService.ts": { statements: 85, branches: 75, functions: 85, lines: 85 },
        "src/core/services/hardware/HardwareEvents.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        // Phase 9A - Upload Framework
        "src/core/services/upload/UploadEngineRegistry.ts": { statements: 95, branches: 80, functions: 100, lines: 95 },
        "src/core/services/upload/UploadManager.ts": { statements: 90, branches: 80, functions: 90, lines: 90 },
        "src/core/services/upload/UploadEvents.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        // Phase 9B - AVR Upload Engine
        "src/core/services/upload/avr/AvrUploadEngine.ts": { statements: 95, branches: 80, functions: 100, lines: 95 },
        "src/core/services/upload/avr/AvrBoardProfile.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "src/core/services/upload/avr/Stk500V1Protocol.ts": { statements: 95, branches: 85, functions: 100, lines: 95 },
        "src/core/services/upload/avr/Stk500V2Protocol.ts": { statements: 90, branches: 80, functions: 100, lines: 90 },
        // Phase 9C - Toolchain & Backend Abstraction
        "src/core/services/upload/UploaderBackendRegistry.ts": { statements: 90, branches: 80, functions: 90, lines: 90 },
        "src/core/services/upload/ToolchainManager.ts": { statements: 90, branches: 80, functions: 90, lines: 90 },
        "src/core/services/upload/backends/AvrdudeBackend.ts": { statements: 95, branches: 80, functions: 100, lines: 95 },
        "src/core/services/upload/backends/MockBackend.ts": { statements: 90, branches: 80, functions: 90, lines: 90 },
        // Phase 10 - ESP32 Upload Engine
        "src/core/services/upload/esp32/Esp32UploadEngine.ts": { statements: 95, branches: 80, functions: 100, lines: 95 },
        "src/core/services/upload/esp32/EsptoolProtocol.ts": { statements: 95, branches: 80, functions: 100, lines: 95 },
        "src/core/services/upload/esp32/EspResetStrategy.ts": { statements: 95, branches: 80, functions: 100, lines: 95 },
        "src/core/services/upload/esp32/EspBootMode.ts": { statements: 95, branches: 80, functions: 100, lines: 95 },
        "src/core/services/upload/backends/EsptoolBackend.ts": { statements: 95, branches: 80, functions: 100, lines: 95 },
        // Phase 11 - Build System
        "src/core/services/build/BuildEngineRegistry.ts": { statements: 95, branches: 80, functions: 100, lines: 95 },
        "src/core/services/build/BuildManager.ts": { statements: 90, branches: 80, functions: 90, lines: 90 },
        "src/core/services/build/BuildCache.ts": { statements: 95, branches: 80, functions: 100, lines: 95 },
        "src/core/services/build/MockBuildEngine.ts": { statements: 90, branches: 80, functions: 90, lines: 90 },
      },
      reporter: ["text", "html", "lcov"],
    },
  },
});
