import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "node",
    include: ["src/**/*.test.ts"],
    coverage: {
      provider: "v8",
      include: [
        "src/core/di/ServiceContainer.ts",
        "src/core/services/extension/BlockRegistry.ts",
        "src/core/services/extension/GeneratorRegistry.ts",
        "src/core/services/extension/CategoryRegistry.ts",
        "src/core/services/extension/ComponentRegistry.ts",
        "src/core/services/extension/ValidationRegistry.ts",
        "src/core/services/extension/LibraryRegistry.ts",
        "src/core/services/extension/ExampleRegistry.ts",
        "src/core/services/extension/AssetRegistry.ts",
        "src/core/services/extension/CommandRegistry.ts",
        "src/core/services/extension/EventBus.ts",
        "src/core/services/extension/ExtensionContext.ts",
        "src/core/services/extension/ExtensionLoader.ts",
        "src/core/services/extension/ExtensionManager.ts",
        "src/core/services/logging/LoggerService.ts",
        "src/core/services/settings/SettingsManager.ts",
        "src/core/services/theme/ThemeService.ts",
        "src/core/services/i18n/LanguageManager.ts",
        "src/core/services/notification/NotificationService.ts",
        "src/core/services/dialog/DialogService.ts",
        "src/core/services/error/ErrorHandler.ts",
        "src/core/services/hardware/connections/USBConnection.ts",
        "src/core/services/hardware/connections/SerialConnection.ts",
        "src/core/services/hardware/connections/BluetoothConnection.ts",
        "src/core/services/hardware/connections/WiFiConnection.ts",
        "src/core/services/hardware/HardwareManager.ts",
        "src/core/services/port/PortManager.ts",
        "src/core/services/device/DeviceManager.ts",
        "src/core/services/compatibility/CompatibilityService.ts",
        "src/core/services/hardware/HardwareEvents.ts",
      ],
      exclude: [
        "src/**/*.test.ts",
        "src/**/*.d.ts",
        "src/core/types/**",
      ],
      thresholds: {
        "src/core/di/ServiceContainer.ts": { statements: 95, branches: 90, functions: 100, lines: 95 },
        "src/core/services/extension/BlockRegistry.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "src/core/services/extension/GeneratorRegistry.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "src/core/services/extension/CategoryRegistry.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "src/core/services/extension/ComponentRegistry.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "src/core/services/extension/LibraryRegistry.ts": { statements: 100, branches: 85, functions: 100, lines: 100 },
        "src/core/services/extension/ExampleRegistry.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
        "src/core/services/extension/AssetRegistry.ts": { statements: 80, branches: 50, functions: 100, lines: 80 },
        "src/core/services/extension/EventBus.ts": { statements: 95, branches: 90, functions: 100, lines: 95 },
        "src/core/services/extension/ExtensionContext.ts": { statements: 55, branches: 0, functions: 65, lines: 55 },
        "src/core/services/extension/ExtensionLoader.ts": { statements: 70, branches: 35, functions: 50, lines: 75 },
        "src/core/services/extension/ExtensionManager.ts": { statements: 60, branches: 50, functions: 75, lines: 60 },
        "src/core/services/extension/ValidationRegistry.ts": { statements: 35, branches: 15, functions: 65, lines: 35 },
        "src/core/services/logging/LoggerService.ts": { statements: 95, branches: 65, functions: 95, lines: 95 },
        "src/core/services/settings/SettingsManager.ts": { statements: 90, branches: 75, functions: 80, lines: 90 },
        "src/core/services/theme/ThemeService.ts": { statements: 85, branches: 50, functions: 85, lines: 85 },
        "src/core/services/i18n/LanguageManager.ts": { statements: 85, branches: 65, functions: 85, lines: 85 },
        "src/core/services/notification/NotificationService.ts": { statements: 90, branches: 80, functions: 90, lines: 90 },
        "src/core/services/dialog/DialogService.ts": { statements: 90, branches: 70, functions: 90, lines: 90 },
        "src/core/services/error/ErrorHandler.ts": { statements: 80, branches: 65, functions: 80, lines: 85 },
        "src/core/services/hardware/connections/USBConnection.ts": { statements: 85, branches: 70, functions: 95, lines: 95 },
        "src/core/services/hardware/connections/SerialConnection.ts": { statements: 60, branches: 50, functions: 40, lines: 60 },
        "src/core/services/hardware/connections/BluetoothConnection.ts": { statements: 50, branches: 50, functions: 30, lines: 50 },
        "src/core/services/hardware/connections/WiFiConnection.ts": { statements: 50, branches: 50, functions: 30, lines: 50 },
        "src/core/services/hardware/HardwareManager.ts": { statements: 90, branches: 75, functions: 90, lines: 90 },
        "src/core/services/port/PortManager.ts": { statements: 90, branches: 75, functions: 90, lines: 90 },
        "src/core/services/device/DeviceManager.ts": { statements: 90, branches: 65, functions: 90, lines: 90 },
        "src/core/services/compatibility/CompatibilityService.ts": { statements: 85, branches: 75, functions: 85, lines: 85 },
        "src/core/services/hardware/HardwareEvents.ts": { statements: 100, branches: 100, functions: 100, lines: 100 },
      },
      reporter: ["text", "html", "lcov"],
    },
  },
});
